# Generated by Django 4.2.7 on 2026-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('traveler', 'Traveler'), ('admin', 'Admin')], default='traveler', max_length=20),
        ),
    ]
